# DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5000/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 1234

# Mybatis
mybatis:
  type-aliases-package: com.flab.daitso.mapper
  mapper-locations: classpath:mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true
