# DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daitso?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: password

# MyBatis
mybatis:
  type-aliases-package: com.flab.daitso.mapper
  mapper-locations: classpath:mapper/*.xml